[build]
  publish = "./dist"
  command = "npx pnpm i --frozen-lockfile --store=node_modules/.pnpm-store && npx pnpm run build"

[build.environment]
  NODE_VERSION = "18"
  PYTHON_VERSION = "3.8"
  COMMIT_REF = __COMMIT__

[dev]
  publish = "dist/"
  targetPort = 5000

[functions]
  directory = "functions"
  node_bundler = "esbuild"
